# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the distance between events.
#'
#' @useDynLib nphawkes
#' @param x A vector of length n, holding the longitudes of interest
#' @param y A vector of length n, holding the latitudes of interest
#' @param n A single integer indicating the number of events  
#' @return dist A vector of length n(n-1)/2, holding the distance between events
#' @export
ComputeDistance <- function(x, y, n) {
    .Call('nphawkes_ComputeDistance', PACKAGE = 'nphawkes', x, y, n)
}

#' Compute the time differences between events.
#'
#' @useDynLib nphawkes
#' @param x A vector of length n, holding the times of interest
#' @return tdiff A vector of length n(n-1)/2, holding the time differences
#' @export
ComputeTimeDifference <- function(x) {
    .Call('nphawkes_ComputeTimeDifference', PACKAGE = 'nphawkes', x)
}

#' Computes the triggering function for a marked spatial temporal hawkes point process with a homonogenous and stationary background rate.
#'
#' @useDynLib nphawkes
#' @param g A vector of length n(n-1)/2, holding the triggering probabilities for time
#' @param f A vector of length n(n-1)/2, holding the triggering probabilities for distance
#' @param kp A vector of length n(n-1)/2, holding the triggering probabilities for mark productivity
#' @param mu A single numeric of length 1, holding the background rate
#' @param n A single integer indicating the number of events in the catalog.
#' @return pbNew A vector of background probabilities
#' @return ptNew A vector of triggering probabilities
#' @export
ComputeTriggeringMarkedSpatialTemporal <- function(g, f, kp, mu, n) {
    .Call('nphawkes_ComputeTriggeringMarkedSpatialTemporal', PACKAGE = 'nphawkes', g, f, kp, mu, n)
}

#' Computes the triggering function for a marked spatial temporal hawkes point process with a inhomonogenous and stationary background rate.
#'
#' @useDynLib nphawkes
#' @param g A vector of length n(n-1)/2, holding the triggering probabilities for time
#' @param f A vector of length n(n-1)/2, holding the triggering probabilities for distance
#' @param kp A vector of length n(n-1)/2, holding the triggering probabilities for mark productivity
#' @param mu A vector of length n, holding the background rate in the grid of each event
#' @param n A single integer indicating the number of events in the catalog.
#' @return pbNew A vector of background probabilities
#' @return ptNew A vector of triggering probabilities
#' @export
ComputeTriggeringMarkedSpatialTemporalNH <- function(g, f, kp, mu, n) {
    .Call('nphawkes_ComputeTriggeringMarkedSpatialTemporalNH', PACKAGE = 'nphawkes', g, f, kp, mu, n)
}

#' Computes the triggering function for a spatial temporal hawkes point process with a homonogenous and stationary background rate.
#' @useDynLib nphawkes
#' @param g A vector of length n(n-1)/2, holding the triggering probabilities for time
#' @param f A vector of length n(n-1)/2, holding the triggering probabilities for distance
#' @param mu A single numeric of length 1, holding the background rate
#' @param n A single integer indicating the number of events in the catalog.
#' @return pbNew A vector of background probabilities
#' @return ptNew A vector of triggering probabilities
#' @export
ComputeTriggeringSpatialTemporal <- function(g, f, mu, n) {
    .Call('nphawkes_ComputeTriggeringSpatialTemporal', PACKAGE = 'nphawkes', g, f, mu, n)
}

#' Initialize triggering and background probabilities 
#'
#' @useDynLib nphawkes
#' @param g a vector of length n(n-1)/2, holding the triggering probabilities
#' @param mu a numeric of length 1, holding the background rate
#' @param n A single integer indicating the number of events in the catalog.
#' @return pbNew a vector of background probabilities
#' @return ptNew a vector of triggering probabilities
#' @export
ComputeTriggeringTemporal <- function(g, mu, n) {
    .Call('nphawkes_ComputeTriggeringTemporal', PACKAGE = 'nphawkes', g, mu, n)
}

#' Computes the triggering function for a spatial temporal hawkes point process with a homonogenous and stationary background rate.
#' @useDynLib nphawkes
#' @param g A vector of length n(n-1)/2, holding the triggering probabilities for time
#' @param mu A vector of length n(n-1)/2, holding the background probabilities associated with the grid of each point
#' @param kp A single number representing the mean number of events triggered per day
#' @param n A single integer indicating the number of events in the catalog.
#' @export
ComputeTriggeringTemporalNS <- function(g, kp, mu, n) {
    .Call('nphawkes_ComputeTriggeringTemporalNS', PACKAGE = 'nphawkes', g, kp, mu, n)
}

#' Computes the distance from one events to all other events and sort them is ascending order
#'
#' @useDynLib nphawkes
#' @param x1 A vector of length n, holding the longitudes of interest
#' @param y1 A vector of length n, holding the latitude of interest
#' @param j A single integer indicating the position of the origin event
#' @return dist1 A sorted vector of distances from the origin event
#' @export
distanceFrom <- function(x1, y1, j) {
    .Call('nphawkes_distanceFrom', PACKAGE = 'nphawkes', x1, y1, j)
}

#' Computes the distance from one events to all other events and sort them is ascending order
#'
#' @useDynLib nphawkes
#' @param x0 A single double indicating the position of the origin event
#' @param y0 A single double indicating the position of the origin event
#' @param x1 A vector of length n, holding the longitudes of interest
#' @param y1 A vector of length n, holding the latitude of interest
#' @return dist A vector of distances from the origin event
#' @export
distanceFrom2 <- function(x0, y0, x1, y1) {
    .Call('nphawkes_distanceFrom2', PACKAGE = 'nphawkes', x0, y0, x1, y1)
}

#' Computes the grid locations of each event for the background rate 
#'
#' @useDynLib nphawkes
#' @param nbins_x A single number holding the number of longitudes bins for the background rate
#' @param nbins_y A single number holding the number of latitude bins for the background rate
#' @param x A vector of length n, holding the longitudes of interest
#' @param y A vector of length n, holding the latitude of interest
#' @param grid_x A vector holding the grid positions for the longitudes bins of the background rate
#' @param grid_y A vector holding the grid positions for the latitude bins of the background rate
#' @param n A single integer indicating the number of events in the catalog
#' @return D A vector of length nbins_x  * nbins_y holding vectors with event indices if they fall within the grid cell 
#' @export
getBackgroudPosition <- function(nbins_x, nbins_y, x, y, grid_x, grid_y, n) {
    .Call('nphawkes_getBackgroudPosition', PACKAGE = 'nphawkes', nbins_x, nbins_y, x, y, grid_x, grid_y, n)
}

#' Computes the background probability associated with each point in the catalog
#'
#' @useDynLib nphawkes
#' @param x A vector of length n, holding the longitudes of interest
#' @param y A vector of length n, holding the latitude of interest
#' @param t A Single number, holding the maximum time of interest
#' @param pbNew A vector of length n, holding the background probabilities
#' @param nn An integer for the n-th nearest neighbor to use in background smoothing
#' @param nbins_x A single number holding the number of longitudes bins for the background rate
#' @param nbins_y A single number holding the number of latitude bins for the background rate
#' @param grid_x A vector holding the grid positions for the longitudes bins of the background rate
#' @param grid_y A vector holding the grid positions for the latitude bins of the background rate
#' @param delta_x A single number holding the bin width longitudes bins for the background rate
#' @param delta_y A single number holding the bin height of latitude bins for the background rate
#' @param n A single integer indicating the number of events in the catalog
#' @return mu A vector of length n holding the new background probabilities 
#' @export
getBackground <- function(x, y, t, pbNew, nn, nbins_x, nbins_y, grid_x, grid_y, delta_x, delta_y, n) {
    .Call('nphawkes_getBackground', PACKAGE = 'nphawkes', x, y, t, pbNew, nn, nbins_x, nbins_y, grid_x, grid_y, delta_x, delta_y, n)
}

#' Computes the background probability associated with each point in the catalog
#'
#' @useDynLib nphawkes
#' @param t A vector of length n, holding the times of interest
#' @param pbNew A vector of length n, holding the background probabilities
#' @param nn A single number holding the nearest neighbor bandwith used in the kernel
#' @param nbins_mu A single number holding the number of time bins for the background rate
#' @param grid_mu A vector holding the grid positions for the time  bins of the background rate
#' @param delta_mu A single number holding the bin size of the time bins for the background rate
#' @param n A single integer indicating the number of events in the catalog
#' @export
getBackgroundT <- function(t, pbNew, nn, nbins_mu, grid_mu, delta_mu, n) {
    .Call('nphawkes_getBackgroundT', PACKAGE = 'nphawkes', t, pbNew, nn, nbins_mu, grid_mu, delta_mu, n)
}

#'  Determines the distance bins for use in the triggering function
#'
#' @useDynLib nphawkes
#' @param nbins_r The number of distance bins on which to estimate the spatial triggering of the Hawkes Point Process Model
#' @param dist A vector of length n(n-1)/2 holding the distance between events 
#' @param grid_r The grid on which the spatial triggering distribution is estimated
#' @export
getDistanceBins <- function(nbins_r, dist, grid_r) {
    .Call('nphawkes_getDistanceBins', PACKAGE = 'nphawkes', nbins_r, dist, grid_r)
}

#'  Determines the magnitude bins for use in the triggering function
#'
#' @useDynLib nphawkes
#' @param nbins_m The number of distance bins on which to estimate the magnitude productivity of the Hawkes Point Process Model
#' @param mags A vector of length n(n-1)/2 holding the mainshock magnitudes between events 
#' @param grid_m The grid on which the magnitude productivity is estimated
#' @export
getMagnitudeBins <- function(nbins_m, mags, grid_m) {
    .Call('nphawkes_getMagnitudeBins', PACKAGE = 'nphawkes', nbins_m, mags, grid_m)
}

#' Generates marks for all sequences of events in the catalog
#'
#' @useDynLib nphawkes
#' @param m A vector of length n, holding the marks
#' @param n A single integer indicating the number of events  
#' @return mags A vector of length n(n-1)/2 containing the marks associated with each triggering probability
#' @export
getMags <- function(m, n) {
    .Call('nphawkes_getMags', PACKAGE = 'nphawkes', m, n)
}

#' Determines the distance of the specified nearest neighbor
#'
#' @useDynLib nphawkes
#' @param x A vector of length n, holding the longitudes of interest
#' @param y A vector of length n, holding the latitude of interest
#' @param np A single integer indicating the nth nearest neighbor
#' @param n A single integer indicating the  number of events
#' @return nn A vector of nearest neighbor distances
#' @export
getNN <- function(x, y, np, n) {
    .Call('nphawkes_getNN', PACKAGE = 'nphawkes', x, y, np, n)
}

#'  Determines the time bins for use in the triggering function
#'
#' @useDynLib nphawkes
#' @param nbins_t The number of time bins on which to estimate the temporal triggering of the Hawkes Point Process Model
#' @param time A vector of length n(n-1)/2 holding the time between events 
#' @param grid_t The grid on which the temporal triggering distribution is estimated
#' @export
getTimeBins <- function(nbins_t, time, grid_t) {
    .Call('nphawkes_getTimeBins', PACKAGE = 'nphawkes', nbins_t, time, grid_t)
}

#' Initialize triggering and background probabilities 
#'
#' @useDynLib nphawkes
#' @param n A single integer indicating the number of events in the catalog.
#' @export
initProb <- function(n) {
    .Call('nphawkes_initProb', PACKAGE = 'nphawkes', n)
}

#' Calculates a probability weighted normal kernel
#'
#' @useDynLib nphawkes
#' @param prob A single value on which to calculate the kernel 
#' @param x A single number holding the longitude of interest
#' @param y A single number holding the latitude of interest
#' @param bwd A single number holding the bandwith used in the kernel
#' @return value A single value of the kernel density at the point of interest
#' @export
pKern <- function(prob, x, y, bwd) {
    .Call('nphawkes_pKern', PACKAGE = 'nphawkes', prob, x, y, bwd)
}

#' Kernel smoothing for nonstationary temporal background rate
#'
#' @useDynLib nphawkes
#' @param prob A single value on which to calculate the kernel 
#' @param t A single number holding the time of interest
#' @param bwd A single number holding the bandwith used in the kernel
#' @export 
pKernT <- function(prob, t, bwd) {
    .Call('nphawkes_pKernT', PACKAGE = 'nphawkes', prob, t, bwd)
}

#' Utility function to replace elements in vector mu with indices specified in vector of vectors D 
#'
#' @useDynLib nphawkes
#' @param mu A vector of length nbins_x  * nbins_y holding the background rate in each cell
#' @param D A vector of length nbins_x  * nbins_y holding vectors with event indices if they fall within the grid cell 
#' @param n A single integer indicating the number of events in the catalog
#' @return muvec A vector length n, holding the updated probabilities 
#' @export
replaceMu <- function(mu, D, n) {
    .Call('nphawkes_replaceMu', PACKAGE = 'nphawkes', mu, D, n)
}

#' Utility function to check that the rows of the matrix for the background and triggering probabilities sum to 1
#'
#' @useDynLib nphawkes
#' @param vt A vector of length n(n-1)2, holding the triggering probabilities
#' @param vb A vector of length n, holding the background probabilities
#' @param sz A single integer indicating the number of events  
#' @export
sumProbs <- function(vt, vb, sz) {
    .Call('nphawkes_sumProbs', PACKAGE = 'nphawkes', vt, vb, sz)
}

#' Utility function to sum a vector
#'
#' @useDynLib nphawkes
#' @param v A vector
#' @return sum the sum
#' @export
sumVector <- function(v) {
    .Call('nphawkes_sumVector', PACKAGE = 'nphawkes', v)
}

